const dummyReviews = [
  {
    level: "newbie",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User1",
    movieName: "기생충",
    content:
      "정말 예상치 못한 반전이 많아서 흥미진진했어요! 마지막까지 긴장감을 놓을 수 없는 영화였습니다.",
    isBlur: false,
    theUpCnt: 23,
    theDownCnt: 3,
    theIsUp: false,
    theIsDown: false,
    commentCnt: 5,
    starRate: 3.5,
    upClick: () => console.log("Upvote clicked for User1"),
    downClick: () => console.log("Downvote clicked for User1"),
  },
  {
    level: "beginner",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User2",
    movieName: "인터스텔라",
    content:
      "개인적으로는 조금 느린 감이 있었지만, 영상미가 대단했습니다. 비주얼을 중요하게 생각하는 분들에게 추천합니다.",
    isBlur: true,
    theUpCnt: 10,
    theDownCnt: 8,
    theIsUp: true,
    theIsDown: false,
    commentCnt: 2,
    starRate: 4.0,
    upClick: () => console.log("Upvote clicked for User2"),
    downClick: () => console.log("Downvote clicked for User2"),
  },
  {
    level: "intermediate",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User3",
    movieName: "매트릭스",
    content:
      "SF를 좋아하는 분이라면 꼭 보셔야 할 영화! 철학적인 메시지와 액션이 훌륭하게 조화되어 있습니다.",
    isBlur: false,
    theUpCnt: 50,
    theDownCnt: 2,
    theIsUp: false,
    theIsDown: true,
    commentCnt: 10,
    starRate: 4.5,
    upClick: () => console.log("Upvote clicked for User3"),
    downClick: () => console.log("Downvote clicked for User3"),
  },
  {
    level: "expert",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User4",
    movieName: "명량",
    content:
      "기대했던 것과는 조금 달랐지만, 여전히 흥미로운 요소가 많았습니다. 배우들의 연기가 특히 인상적이었어요.",
    isBlur: false,
    theUpCnt: 12,
    theDownCnt: 15,
    theIsUp: false,
    theIsDown: false,
    commentCnt: 1,
    starRate: 3.0,
    upClick: () => console.log("Upvote clicked for User4"),
    downClick: () => console.log("Downvote clicked for User4"),
  },
  {
    level: "master",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User5",
    movieName: "올드보이",
    content:
      "걸작 그 자체입니다! 감동적이고 놀라운 스토리 전개로 인해 손에 땀을 쥐게 했어요. 강력 추천합니다!",
    isBlur: true,
    theUpCnt: 80,
    theDownCnt: 0,
    theIsUp: true,
    theIsDown: false,
    commentCnt: 25,
    starRate: 5.0,
    upClick: () => console.log("Upvote clicked for User5"),
    downClick: () => console.log("Downvote clicked for User5"),
  },
  {
    level: "movieFan",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User6",
    movieName: "관상",
    content: "중간에 졸았습니다... 스토리가 제 스타일은 아니었어요.",
    isBlur: false,
    theUpCnt: 5,
    theDownCnt: 20,
    theIsUp: false,
    theIsDown: true,
    commentCnt: 3,
    starRate: 2.0,
    upClick: () => console.log("Upvote clicked for User6"),
    downClick: () => console.log("Downvote clicked for User6"),
  },
  {
    level: "couchCritic",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User7",
    movieName: "해리포터",
    content:
      "캐릭터들과 스토리라인이 너무 좋았어요. 특히 세계관이 매력적이었습니다.",
    isBlur: true,
    theUpCnt: 35,
    theDownCnt: 4,
    theIsUp: true,
    theIsDown: false,
    commentCnt: 12,
    starRate: 4.2,
    upClick: () => console.log("Upvote clicked for User7"),
    downClick: () => console.log("Downvote clicked for User7"),
  },
  {
    level: "movieBuff",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User8",
    movieName: "트랜스포머",
    content: "그냥 그랬어요. 특별한 점은 없었던 것 같습니다.",
    isBlur: false,
    theUpCnt: 18,
    theDownCnt: 10,
    theIsUp: false,
    theIsDown: false,
    commentCnt: 6,
    starRate: 3.8,
    upClick: () => console.log("Upvote clicked for User8"),
    downClick: () => console.log("Downvote clicked for User8"),
  },
  {
    level: "movieMaster",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User9",
    movieName: "반지의 제왕",
    content: "다시는 보고 싶지 않을 것 같아요. 제 취향은 아니었습니다.",
    isBlur: false,
    theUpCnt: 3,
    theDownCnt: 30,
    theIsUp: false,
    theIsDown: true,
    commentCnt: 0,
    starRate: 2.5,
    upClick: () => console.log("Upvote clicked for User9"),
    downClick: () => console.log("Downvote clicked for User9"),
  },
  {
    level: "movieGod",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User10",
    movieName: "타이타닉",
    content: "고전 장르의 신선한 해석이었습니다! 너무 감동적이었어요.",
    isBlur: true,
    theUpCnt: 60,
    theDownCnt: 5,
    theIsUp: true,
    theIsDown: false,
    commentCnt: 8,
    starRate: 4.8,
    upClick: () => console.log("Upvote clicked for User10"),
    downClick: () => console.log("Downvote clicked for User10"),
  },
];

export default dummyReviews;
