const dummyReviews = [
  {
    width: "100%",
    level: "newbie",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User1",
    content: "Great movie with unexpected twists!",
    isBlur: false,
    theUpCnt: 23,
    theDownCnt: 3,
    theIsUp: false,
    theIsDown: false,
    commentCnt: 5,
    starRate: 3.5,
    upClick: () => console.log("Upvote clicked for User1"),
    downClick: () => console.log("Downvote clicked for User1"),
  },
  {
    width: "100%",
    level: "beginner",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User2",
    content: "A bit too slow for my taste, but the visuals were stunning.",
    isBlur: true,
    theUpCnt: 10,
    theDownCnt: 8,
    theIsUp: true,
    theIsDown: false,
    commentCnt: 2,
    starRate: 4.0,
    upClick: () => console.log("Upvote clicked for User2"),
    downClick: () => console.log("Downvote clicked for User2"),
  },
  {
    width: "100%",
    level: "intermediate",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User3",
    content: "Highly recommended for sci-fi lovers!",
    isBlur: false,
    theUpCnt: 50,
    theDownCnt: 2,
    theIsUp: false,
    theIsDown: true,
    commentCnt: 10,
    starRate: 4.5,
    upClick: () => console.log("Upvote clicked for User3"),
    downClick: () => console.log("Downvote clicked for User3"),
  },
  {
    width: "100%",
    level: "expert",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User4",
    content: "Not what I expected, but still entertaining.",
    isBlur: false,
    theUpCnt: 12,
    theDownCnt: 15,
    theIsUp: false,
    theIsDown: false,
    commentCnt: 1,
    starRate: 3.0,
    upClick: () => console.log("Upvote clicked for User4"),
    downClick: () => console.log("Downvote clicked for User4"),
  },
  {
    width: "100%",
    level: "master",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User5",
    content: "An absolute masterpiece!",
    isBlur: true,
    theUpCnt: 80,
    theDownCnt: 0,
    theIsUp: true,
    theIsDown: false,
    commentCnt: 25,
    starRate: 5.0,
    upClick: () => console.log("Upvote clicked for User5"),
    downClick: () => console.log("Downvote clicked for User5"),
  },
  {
    width: "100%",
    level: "movieFan",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User6",
    content: "I fell asleep halfway through...",
    isBlur: false,
    theUpCnt: 5,
    theDownCnt: 20,
    theIsUp: false,
    theIsDown: true,
    commentCnt: 3,
    starRate: 2.0,
    upClick: () => console.log("Upvote clicked for User6"),
    downClick: () => console.log("Downvote clicked for User6"),
  },
  {
    width: "100%",
    level: "couchCritic",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User7",
    content: "Loved the characters and the storyline.",
    isBlur: true,
    theUpCnt: 35,
    theDownCnt: 4,
    theIsUp: true,
    theIsDown: false,
    commentCnt: 12,
    starRate: 4.2,
    upClick: () => console.log("Upvote clicked for User7"),
    downClick: () => console.log("Downvote clicked for User7"),
  },
  {
    width: "100%",
    level: "movieBuff",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User8",
    content: "It was okay, nothing extraordinary.",
    isBlur: false,
    theUpCnt: 18,
    theDownCnt: 10,
    theIsUp: false,
    theIsDown: false,
    commentCnt: 6,
    starRate: 3.8,
    upClick: () => console.log("Upvote clicked for User8"),
    downClick: () => console.log("Downvote clicked for User8"),
  },
  {
    width: "100%",
    level: "movieMaster",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User9",
    content: "Wouldn't watch it again.",
    isBlur: false,
    theUpCnt: 3,
    theDownCnt: 30,
    theIsUp: false,
    theIsDown: true,
    commentCnt: 0,
    starRate: 2.5,
    upClick: () => console.log("Upvote clicked for User9"),
    downClick: () => console.log("Downvote clicked for User9"),
  },
  {
    width: "100%",
    level: "movieGod",
    proflieImg: "https://via.placeholder.com/50",
    profileName: "User10",
    content: "A refreshing take on a classic genre!",
    isBlur: true,
    theUpCnt: 60,
    theDownCnt: 5,
    theIsUp: true,
    theIsDown: false,
    commentCnt: 8,
    starRate: 4.8,
    upClick: () => console.log("Upvote clicked for User10"),
    downClick: () => console.log("Downvote clicked for User10"),
  },
];

export default dummyReviews;
